version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: './frontend'
      dockerfile: Dockerfile.dev
    expose:
      - 80
    links:
      - "backend"
    depends_on:
      - backend
    networks:
      - net
    #     ipv4_address: 192.168.240.3

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - net
    #       ipv4_address: 192.168.240.2
  nginx:
    image: nginx:1.17
    restart: unless-stopped
    links:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - net

  watchtower:
     image: containrrr/watchtower
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     restart: unless-stopped
     command: --interval 300

networks:
  net:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 192.168.240.0/24

  